"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense, useEffect, useState } from "react";
import dynamic from "next/dynamic";

import Head from "next/head";
import Footer from "@/components/Footer/Footer";
const NavBar = dynamic(() => import("@/components/NavBar/NavBar"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Serif:wght@300;400;500;600;700;800&family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <body className="overflow-x-hidden">
        <Suspense fallback={<></>}>
          <NavBar />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
